"use client";

import { OnSaveContext } from "@/context/OnSaveContext";
import { useParams, useSearchParams } from "next/navigation";
import { useCallback, useContext, useEffect, useRef, useState } from "react";
import PlaygroundHeader from "../_components/PlaygroundHeader";
import ChatSection from "../_components/ChatSection";
import CodeSandboxWorkSpace from "../_components/CodeSandboxWorkSpace";
import axios from "axios";
import { extractHtmlContent } from "@/lib/html-utils";
import { toast } from "sonner";

export type Messages = {
  role: string;
  content: string;
  image?: string;
  imageUrl?: string;
};

const DesignInstructions = `You are an expert front-end developer building and improving live website previews in an AI website builder.

The preview runs in an isolated browser iframe with pre-loaded CDN assets.
You output HTML for the <body> only — never <html>, <head>, <title>, or external <script src="..."> tags (libraries are already injected).

You CANNOT use React, Vue, Svelte, TypeScript, CSS modules, npm installs, or build tools — only plain HTML with the libraries below.

**Available libraries (already loaded in preview):**
- Tailwind CSS — utility-first styling
- Flowbite UI — buttons, navbars, modals, forms, cards, tables, accordions, tabs, dropdowns, alerts
- Lucide icons — use <i data-lucide="icon-name"></i> and call lucide.createIcons() in an inline <script> at the end when icons are present
- Chart.js — charts and data visualization
- Swiper — carousels and sliders
- AOS — scroll animations via data-aos attributes
- GSAP — advanced animations
- Lottie — vector animations via lottie.loadAnimation()
- Tippy.js — tooltips via data-tippy-content

When scraped website data is provided in the user message (e.g. page title, headings, navigation items, paragraphs, sections), you MUST recreate that website's design, layout, and content as closely as possible. Use the scraped data as your source of truth — match the structure, sections, navigation, headings, text content, and overall layout. Do NOT refuse or generate something generic.

When existing website code is provided in a prior system message, treat it as the current state to modify — preserve sections unless the user asks to remove or replace them.

WORKFLOW:
1. Read the user's message and decide: design/code request, or casual conversation?
2. If casual (greetings, general questions, no layout or code asked): reply conversationally — do NOT output HTML.
3. If design/code is requested:
   a. Understand what the user wants built, changed, or improved.
   b. If existing code was provided, modify and extend it — do not discard working sections unless asked.
   c. Output the complete updated body HTML in a single response.

RULES:
- Output only body HTML — no markdown explanations, no preamble, no postamble when generating code.
- Wrap output in a \`\`\`html code fence, or output raw HTML starting with a tag like <main>, <section>, or <div>.
- Use Tailwind CSS with Flowbite components for all UI.
- Primary theme color: blue (e.g. blue-600, blue-700). Apply consistently across buttons, links, accents, and charts.
- Design must be fully responsive: mobile-first, works on phones, tablets, and desktop.
- Use clear visual hierarchy: headings, subheadings, spacing (min py-8 per section), modern typography.
- Placeholder images with descriptive alt text:
  - Light: https://community.softr.io/uploads/db9110/original/2X/7/74e6e7e382d0ff5d7773ca9a87e6f6f8817a68a6.jpeg
  - Dark: https://www.cibaky.com/wp-content/uploads/2015/12/placeholder-3.jpg
- No broken links — use javascript:void(0) instead of "#".
- Include interactive elements where appropriate: dropdowns, accordions, tabs, modals, sliders.
- Initialize Flowbite components, Lucide icons, Swiper, Chart.js, AOS, and Tippy in inline <script> blocks at the end of the output when used.
- Each section should be self-contained unless the user explicitly ties them together.
- Code must be production-ready, visually polished, and professionally structured.`;

const Playground = () => {
  const { projectId } = useParams();
  const params = useSearchParams();
  const frameId = params.get("frameId");
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [messages, setMessages] = useState<Messages[]>([]);
  const [generatedCode, setGeneratedCode] = useState("");
  const hasAutoGenerated = useRef(false);
  const saveContext = useContext(OnSaveContext);

  useEffect(() => {
    hasAutoGenerated.current = false;
    if (frameId) GetFrameDetails();
  }, [frameId]);

  const SaveMessages = async (msgs: Messages[]) => {
    if (!frameId) return;
    await axios.put("/api/chats", {
      frameId: String(frameId),
      messages: msgs,
    });
  };

  const SaveGeneratedCode = async (code: string) => {
    const cleanCode = extractHtmlContent(code);
    await axios.put("/api/frames", {
      frameId: String(frameId),
      designCode: cleanCode,
      projectId,
    });
    return cleanCode;
  };

  const GenerateResponse = async (
    currentMessages: Messages[],
    existingCode = generatedCode,
  ) => {
    setLoading(true);

    try {
      const apiMessages: Messages[] = [];

      if (existingCode) {
        apiMessages.push({
          role: "system",
          content: `Here is the current website code to continue or modify:\n\n\`\`\`html\n${extractHtmlContent(existingCode)}\n\`\`\``,
        });
      }

      apiMessages.push({ role: "system", content: DesignInstructions });

      for (const msg of currentMessages) {
        apiMessages.push({ role: msg.role, content: msg.content });
      }

      const lastUserWithImage = [...currentMessages]
        .reverse()
        .find((m) => m.role === "user" && (m.image || m.imageUrl));

      const response = await fetch("/api/ai-model", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: apiMessages,
          imageUrl: lastUserWithImage?.image ?? lastUserWithImage?.imageUrl,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => null);
        throw new Error(errorData?.error || "Failed to generate design");
      }

      const reader = response.body?.getReader();
      if (!reader) throw new Error("No response body");

      const decoder = new TextDecoder();

      let aiResponse = "";
      let codeContent = "";
      let isCode = false;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        aiResponse += chunk;

        if (!isCode && aiResponse.includes("```html")) {
          isCode = true;
          const index = aiResponse.indexOf("```html") + 7;
          codeContent = aiResponse.slice(index);
          setGeneratedCode(extractHtmlContent(codeContent) || codeContent);
        } else if (!isCode && /<\w+[^>]*>/.test(aiResponse)) {
          isCode = true;
          codeContent = aiResponse;
          setGeneratedCode(extractHtmlContent(codeContent) || codeContent);
        } else if (isCode) {
          if (chunk.includes("```")) {
            const endIdx = chunk.indexOf("```");
            codeContent += chunk.slice(0, endIdx);
          } else {
            codeContent += chunk;
          }
          setGeneratedCode(extractHtmlContent(codeContent) || codeContent);
        }
      }

      if (!isCode) {
        const finalMessages = [
          ...currentMessages,
          { role: "assistant", content: aiResponse },
        ];
        setMessages(finalMessages);
        await SaveMessages(finalMessages);
      } else {
        const cleanCode = extractHtmlContent(codeContent);
        setGeneratedCode(cleanCode);
        const finalMessages = [
          ...currentMessages,
          { role: "assistant", content: "Your design has been updated." },
        ];
        setMessages(finalMessages);
        await SaveGeneratedCode(cleanCode);
        await SaveMessages(finalMessages);
      }
    } catch (error) {
      console.error("Generation failed:", error);
      toast.error(
        error instanceof Error ? error.message : "Failed to generate design.",
      );
    } finally {
      setLoading(false);
    }
  };

  const GetFrameDetails = async () => {
    try {
      const result = await axios.get(
        `/api/frames?frameId=${frameId}&projectId=${projectId}`,
      );
      const chatMessages = result.data?.chatMessages ?? [];
      const designCode = extractHtmlContent(result.data?.designCode);
      setMessages(chatMessages);
      setGeneratedCode(designCode);

      const needsGeneration =
        chatMessages.length > 0 &&
        !designCode &&
        chatMessages[chatMessages.length - 1]?.role === "user" &&
        !hasAutoGenerated.current;

      if (needsGeneration) {
        hasAutoGenerated.current = true;
        await GenerateResponse(chatMessages, designCode);
      }
    } catch (error) {
      console.error("Failed to load frame:", error);
      if (axios.isAxiosError(error) && error.response?.status === 404) {
        toast.error("Project not found. Please create a new one.");
      }
    }
  };

  const HandleSave = useCallback(async () => {
    if (!frameId) return;
    setSaving(true);
    try {
      const liveDesign = saveContext?.getDesignHtml() ?? generatedCode;
      const designToSave = liveDesign ? extractHtmlContent(liveDesign) : "";

      await SaveMessages(messages);

      if (designToSave) {
        await SaveGeneratedCode(designToSave);
        setGeneratedCode(designToSave);
      }

      toast.success("Project saved successfully!");
    } catch (error) {
      console.error("Save failed:", error);
      toast.error("Failed to save project.");
    } finally {
      setSaving(false);
    }
  }, [frameId, messages, generatedCode, projectId, saveContext]);

  const SendMessage = async (userInput: string) => {
    let finalPrompt = userInput;

    const trimmed = userInput.trim();
    const isUrl = (() => {
      try {
        if (/^https?:\/\//i.test(trimmed)) {
          new URL(trimmed);
          return true;
        }
        if (/^[\w-]+(\.[\w-]+)+/.test(trimmed) && !trimmed.includes(" ")) {
          new URL(`https://${trimmed}`);
          return true;
        }
        return false;
      } catch {
        return false;
      }
    })();

    if (isUrl) {
      try {
        toast.info("Analyzing website...");
        const scrapeUrl = /^https?:\/\//i.test(trimmed)
          ? trimmed
          : `https://${trimmed}`;
        const scrapeResult = await axios.post("/api/scrape-url", {
          url: scrapeUrl,
        });
        const data = scrapeResult.data;
        let scrapedPrompt = `Recreate a website inspired by ${trimmed}.\n\n`;
        scrapedPrompt += `Here is the extracted content from that website:\n`;
        if (data.title) scrapedPrompt += `- Page Title: ${data.title}\n`;
        if (data.metaDescription)
          scrapedPrompt += `- Description: ${data.metaDescription}\n`;
        if (data.navLinks?.length)
          scrapedPrompt += `- Navigation Items: ${data.navLinks.join(", ")}\n`;
        if (data.headings?.length)
          scrapedPrompt += `- Headings: ${data.headings.join(" | ")}\n`;
        if (data.paragraphs?.length)
          scrapedPrompt += `- Content Sections:\n${data.paragraphs.map((p: string) => `  • ${p}`).join("\n")}\n`;
        if (data.buttons?.length)
          scrapedPrompt += `- Buttons/CTAs: ${data.buttons.join(", ")}\n`;
        if (data.images?.length)
          scrapedPrompt += `- Image Descriptions: ${data.images.join(", ")}\n`;
        if (data.sections?.length)
          scrapedPrompt += `- Page Sections/Landmarks: ${data.sections.join(", ")}\n`;
        scrapedPrompt += `\nGenerate a complete, modern, responsive HTML website (body content only) that recreates this design using Tailwind CSS and Flowbite components. Match the layout, sections, and content structure as closely as possible while making it visually stunning.`;
        finalPrompt = scrapedPrompt;
      } catch (error) {
        console.error("Failed to scrape URL:", error);
        toast.error(
          "Could not analyze the website, generating from URL text...",
        );
        finalPrompt = `Recreate a website similar to ${trimmed}. Generate a complete, modern, responsive HTML website (body content only) using Tailwind CSS and Flowbite components.`;
      }
    }

    const userMessage: Messages = { role: "user", content: finalPrompt };
    const messagesWithUser = [...messages, userMessage];

    setMessages(messagesWithUser);

    try {
      await SaveMessages(messagesWithUser);
    } catch (error) {
      console.error("Failed to save message:", error);
      toast.error("Failed to save message.");
    }

    await GenerateResponse(messagesWithUser);
  };

  return (
    <div className="flex h-screen flex-col overflow-hidden">
      <PlaygroundHeader onSave={HandleSave} saving={saving} />

      <div className="flex min-h-0 flex-1 overflow-hidden">
        <ChatSection
          messages={messages}
          onSend={SendMessage}
          loading={loading}
        />
        <div className="min-h-0 min-w-0 flex-1">
          <CodeSandboxWorkSpace generatedCode={generatedCode} />
        </div>
      </div>
    </div>
  );
};
export default Playground;
